# What Is Pandas?

Pandas is an open-source Python library designed for data manipulation and analysis. It makes working with structured data fast, flexible, and intuitive — especially if you're dealing with CSV files, Excel sheets, SQL tables, JSON, or APIs.

In [56]:
import pandas as pd

dataset = {
    'name':['Subin', 'Rahul', 'Manu'],
    'age':[29, 34, 32]
    
}

df = pd.DataFrame(dataset)
print(df)

    name  age
0  Subin   29
1  Rahul   34
2   Manu   32

In [2]:
import pandas as pd

df = pd.read_csv('orders.csv')
print(df.to_string())

    OrderID      CustomerName                Product     Category  Quantity   Price   OrderDate Shipped       Country
0      1001        John Smith                 Laptop  Electronics         1  1200.0  2024-06-01     Yes           USA
1      1002         Sarah Lee             Headphones  Electronics         2   150.0  2024-06-03      No        Canada
2      1003          Ali Khan           Office Chair    Furniture         1   300.0  2024-06-04     Yes           UAE
3      1004        Alice Wong              Desk Lamp    Furniture         3    45.0  2024-06-05     Yes     Singapore
4      1005     Carlos Mendez               Keyboard  Electronics         2    80.0  2024-06-06      No        Mexico
5      1006      Nora Ibrahim               Notebook   Stationery         5     5.0  2024-06-07     Yes           UAE
6      1007       Emily Davis          Standing Desk    Furniture         1   450.0  2024-06-08     Yes            UK
7      1008        James Park                Monitor  Electronics         2   220.0  2024-06-09      No   South Korea
8      1009       Maria Rossi                    Pen   Stationery        10     1.5  2024-06-10     Yes         Italy
9      1010  Takeshi Nakamura                  Mouse  Electronics         1    35.0  2024-06-11     Yes         Japan
10     1011     Sophie Martin                 Webcam  Electronics         1    85.0  2024-06-12     Yes        France
11     1012         Raj Patel           File Cabinet    Furniture         2   180.0  2024-06-13      No         India
12     1013       Emma Wilson                Stapler   Stationery         3    12.0  2024-06-14     Yes     Australia
13     1014   Diego Rodriguez              USB Drive  Electronics         5    25.0  2024-06-15     Yes         Spain
14     1015         Lisa Chen              Bookshelf    Furniture         1   280.0  2024-06-16      No         China
15     1016      Ahmed Hassan          Printer Paper   Stationery        20     8.0  2024-06-17     Yes         Egypt
16     1017     Anna Kowalski         Wireless Mouse  Electronics         2    45.0  2024-06-18     Yes        Poland
17     1018     Michael Brown         Desk Organizer    Furniture         1    65.0  2024-06-19      No           USA
18     1019       Yuki Tanaka             Calculator  Electronics         1    15.0  2024-06-20     Yes         Japan
19     1020   Fatima Al-Zahra             Whiteboard    Furniture         1   120.0  2024-06-21     Yes  Saudi Arabia
20     1021    David Thompson           Highlighters   Stationery         8     3.5  2024-06-22      No        Canada
21     1022    Isabella Silva      Bluetooth Speaker  Electronics         1    95.0  2024-06-23     Yes        Brazil
22     1023    Oliver Schmidt           Office Plant    Furniture         2    35.0  2024-06-24     Yes       Germany
23     1024        Zara Ahmed           Sticky Notes   Stationery        15     4.0  2024-06-25      No      Pakistan
24     1025    Lucas Anderson           Tablet Stand  Electronics         1    28.0  2024-06-26     Yes        Sweden
25     1026      Chloe Dubois         Paper Shredder  Electronics         1    75.0  2024-06-27     Yes        France
26     1027     Miguel Torres         Desk Chair Mat    Furniture         1    22.0  2024-06-28      No     Argentina
27     1028       Nina Petrov           Binder Clips   Stationery        12     2.5  2024-06-29     Yes        Russia
28     1029      Seo-yeon Kim      Wireless Keyboard  Electronics         1   110.0  2024-06-30     Yes   South Korea
29     1030   Giuseppe Romano          Desk Calendar    Furniture         1    18.0  2024-07-01      No         Italy
30     1031      Amira Hassan                USB Hub  Electronics         1    32.0  2024-07-02     Yes       Morocco
31     1032     Thomas Müller       Document Scanner  Electronics         1   140.0  2024-07-03     Yes       Germany
32     1033   Sofia Rodriguez  Desk Drawer Organizer    Furniture         1    42.0  2024-07-04      No      Colombia
33     1034      Alex Johnson            Index Cards   Stationery       100     0.8  2024-07-05     Yes           USA
34     1035     Yuki Yamamoto          Monitor Stand  Electronics         1    55.0  2024-07-06     Yes         Japan
35     1036     Emma Thompson     Desk Lamp with USB    Furniture         1    68.0  2024-07-07      No            UK
36     1037     Carlos Santos       Wireless Earbuds  Electronics         1   125.0  2024-07-08     Yes      Portugal
37     1038    Leila Mansouri               Desk Pad    Furniture         1    28.0  2024-07-09     Yes          Iran
38     1039        Daniel Kim            Power Strip  Electronics         2    18.0  2024-07-10      No   South Korea
39     1040      Anna Ivanova             Desk Clock    Furniture         1    35.0  2024-07-11     Yes       Ukraine

In [58]:
df.head()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico

In [59]:
df.tail()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       40 non-null     int64
 1   CustomerName  40 non-null     object
 2   Product       40 non-null     object
 3   Category      40 non-null     object
 4   Quantity      40 non-null     int64
 5   Price         40 non-null     float64
 6   OrderDate     40 non-null     object
 7   Shipped       40 non-null     object
 8   Country       40 non-null     object
dtypes: float64(1), int64(2), object(6)
memory usage: 2.9+ KB

In [61]:
df.columns

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country'],
      dtype='object')

In [62]:
df.describe()

           OrderID    Quantity        Price
count    40.000000   40.000000    40.000000
mean   1020.500000    5.450000   106.457500
std      11.690452   15.903475   201.091854
min    1001.000000    1.000000     0.800000
25%    1010.750000    1.000000    18.000000
50%    1020.500000    1.000000    43.500000
75%    1030.250000    2.250000   112.500000
max    1040.000000  100.000000  1200.000000

In [63]:
df.index

RangeIndex(start=0, stop=40, step=1)

In [64]:
df.columns

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country'],
      dtype='object')

In [65]:
df[['Category', 'Country']]

       Category       Country
0   Electronics           USA
1   Electronics        Canada
2     Furniture           UAE
3     Furniture     Singapore
4   Electronics        Mexico
5    Stationery           UAE
6     Furniture            UK
7   Electronics   South Korea
8    Stationery         Italy
9   Electronics         Japan
10  Electronics        France
11    Furniture         India
12   Stationery     Australia
13  Electronics         Spain
14    Furniture         China
15   Stationery         Egypt
16  Electronics        Poland
17    Furniture           USA
18  Electronics         Japan
19    Furniture  Saudi Arabia
20   Stationery        Canada
21  Electronics        Brazil
22    Furniture       Germany
23   Stationery      Pakistan
24  Electronics        Sweden
25  Electronics        France
26    Furniture     Argentina
27   Stationery        Russia
28  Electronics   South Korea
29    Furniture         Italy
30  Electronics       Morocco
31  Electronics       Germany
32    Furniture      Colombia
33   Stationery           USA
34  Electronics         Japan
35    Furniture            UK
36  Electronics      Portugal
37    Furniture          Iran
38  Electronics   South Korea
39    Furniture       Ukraine

In [66]:
pd.__version__

'2.3.2'

In [67]:
df.iloc[0]

OrderID                1001
CustomerName     John Smith
Product              Laptop
Category        Electronics
Quantity                  1
Price                1200.0
OrderDate        2024-06-01
Shipped                 Yes
Country                 USA
Name: 0, dtype: object

In [68]:
df[(df['Category'] == 'Electronics') & (df['Country'] == 'Japan')]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan

In [69]:
df[(df['Category'] == 'Electronics') | (df['Country'] == 'Japan')]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea

In [70]:
df[df['Price'] > 1000]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA

In [71]:
df[df['CustomerName'].str.startswith('A')]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [72]:
df[df['CustomerName'].str.endswith('a')]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [73]:
df[df['Country'].isin(['Japan', 'USA', 'UAE'])]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan

In [74]:
df[~df['Country'].isin(['Japan', 'USA', 'UAE'])]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [75]:
df.loc[df['CustomerName'] == 'Sofia Rodriguez']

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia

In [76]:
df.loc[df['CustomerName'] == 'Sofia Rodriguez', 'Product'] = 'Laptop'

In [77]:
df.loc[df["CustomerName"] == 'Sofia Rodriguez']

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
32,1033,Sofia Rodriguez,Laptop,Furniture,1,42.0,2024-07-04,No,Colombia

In [78]:
df.loc[df['Product'] == 'Headphones']

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada

In [ ]:
df.loc[df['Country'] == 'USA']

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [80]:
df[df['Quantity'] > 2]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [81]:
df[(df['Quantity'] > 2) & (df['Price'] > 20)]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain

In [82]:
df[(df['Quantity'] > 2) | (df['Price'] > 20)]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
32,1033,Sofia Rodriguez,Laptop,Furniture,1,42.0,2024-07-04,No,Colombia
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [87]:
df.loc[df['Country'] == 'USA', 'Country'] = 'United States'

In [88]:
df.loc[df['Country'] == 'United States']

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,United States
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,United States
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,United States

In [89]:
df['Country'] = df['Country'].str.upper()

In [90]:
df['Country']

0     UNITED STATES
1            CANADA
2               UAE
3         SINGAPORE
4            MEXICO
5               UAE
6                UK
7       SOUTH KOREA
8             ITALY
9             JAPAN
10           FRANCE
11            INDIA
12        AUSTRALIA
13            SPAIN
14            CHINA
15            EGYPT
16           POLAND
17    UNITED STATES
18            JAPAN
19     SAUDI ARABIA
20           CANADA
21           BRAZIL
22          GERMANY
23         PAKISTAN
24           SWEDEN
25           FRANCE
26        ARGENTINA
27           RUSSIA
28      SOUTH KOREA
29            ITALY
30          MOROCCO
31          GERMANY
32         COLOMBIA
33    UNITED STATES
34            JAPAN
35               UK
36         PORTUGAL
37             IRAN
38      SOUTH KOREA
39          UKRAINE
Name: Country, dtype: object

In [91]:
df = df.drop(39)

In [92]:
df.tail()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,SOUTH KOREA

In [93]:
df.dropna()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,UNITED STATES
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,CANADA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,SINGAPORE
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,MEXICO
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,SOUTH KOREA
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,ITALY
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,JAPAN
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,FRANCE
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,INDIA
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,AUSTRALIA
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,SPAIN
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,CHINA
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,EGYPT
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,POLAND
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,UNITED STATES
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,JAPAN
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,SAUDI ARABIA
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,CANADA
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,BRAZIL
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,GERMANY
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,PAKISTAN
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,SWEDEN
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,FRANCE
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,ARGENTINA
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,RUSSIA
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,SOUTH KOREA
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,ITALY
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,MOROCCO
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,GERMANY
32,1033,Sofia Rodriguez,Laptop,Furniture,1,42.0,2024-07-04,No,COLOMBIA
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,UNITED STATES
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,SOUTH KOREA

In [95]:
df

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,UNITED STATES
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,CANADA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,SINGAPORE
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,MEXICO
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,SOUTH KOREA
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,ITALY
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,JAPAN
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,FRANCE
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,INDIA
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,AUSTRALIA
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,SPAIN
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,CHINA
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,EGYPT
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,POLAND
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,UNITED STATES
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,JAPAN
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,SAUDI ARABIA
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,CANADA
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,BRAZIL
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,GERMANY
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,PAKISTAN
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,SWEDEN
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,FRANCE
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,ARGENTINA
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,RUSSIA
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,SOUTH KOREA
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,ITALY
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,MOROCCO
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,GERMANY
32,1033,Sofia Rodriguez,Laptop,Furniture,1,42.0,2024-07-04,No,COLOMBIA
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,UNITED STATES
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,SOUTH KOREA

In [ ]:
df.fillna({"OrderID":0}, inplace=0)

In [96]:
df.rename(columns={'OrderID': 'Order ID'}, inplace=0)

,Order ID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,UNITED STATES
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,CANADA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,SINGAPORE
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,MEXICO
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,SOUTH KOREA
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,ITALY
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,JAPAN
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,FRANCE
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,INDIA
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,AUSTRALIA
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,SPAIN
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,CHINA
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,EGYPT
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,POLAND
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,UNITED STATES
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,JAPAN
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,SAUDI ARABIA
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,CANADA
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,BRAZIL
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,GERMANY
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,PAKISTAN
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,SWEDEN
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,FRANCE
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,ARGENTINA
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,RUSSIA
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,SOUTH KOREA
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,ITALY
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,MOROCCO
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,GERMANY
32,1033,Sofia Rodriguez,Laptop,Furniture,1,42.0,2024-07-04,No,COLOMBIA
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,UNITED STATES
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,SOUTH KOREA

In [97]:
df['Country'].value_counts()

Country
UNITED STATES    3
JAPAN            3
SOUTH KOREA      3
UAE              2
CANADA           2
ITALY            2
UK               2
FRANCE           2
GERMANY          2
SINGAPORE        1
MEXICO           1
INDIA            1
AUSTRALIA        1
CHINA            1
SPAIN            1
EGYPT            1
POLAND           1
SAUDI ARABIA     1
BRAZIL           1
PAKISTAN         1
SWEDEN           1
ARGENTINA        1
RUSSIA           1
MOROCCO          1
COLOMBIA         1
PORTUGAL         1
IRAN             1
Name: count, dtype: int64

In [98]:
df

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,UNITED STATES
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,CANADA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,SINGAPORE
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,MEXICO
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,SOUTH KOREA
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,ITALY
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,JAPAN
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,FRANCE
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,INDIA
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,AUSTRALIA
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,SPAIN
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,CHINA
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,EGYPT
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,POLAND
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,UNITED STATES
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,JAPAN
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,SAUDI ARABIA
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,CANADA
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,BRAZIL
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,GERMANY
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,PAKISTAN
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,SWEDEN
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,FRANCE
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,ARGENTINA
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,RUSSIA
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,SOUTH KOREA
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,ITALY
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,MOROCCO
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,GERMANY
32,1033,Sofia Rodriguez,Laptop,Furniture,1,42.0,2024-07-04,No,COLOMBIA
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,UNITED STATES
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,SOUTH KOREA

In [ ]:
df.groupby("Country").Quantity.sum()
# summarize data based on categories

Country
ARGENTINA          1
AUSTRALIA          3
BRAZIL             1
CANADA            10
CHINA              1
COLOMBIA           1
EGYPT             20
FRANCE             2
GERMANY            3
INDIA              2
IRAN               1
ITALY             11
JAPAN              3
MEXICO             2
MOROCCO            1
PAKISTAN          15
POLAND             2
PORTUGAL           1
RUSSIA            12
SAUDI ARABIA       1
SINGAPORE          3
SOUTH KOREA        5
SPAIN              5
SWEDEN             1
UAE                6
UK                 2
UNITED STATES    102
Name: Quantity, dtype: int64

In [101]:
df.groupby('Product')['Price'].sum()

Product
Binder Clips             2.5
Bluetooth Speaker       95.0
Bookshelf              280.0
Calculator              15.0
Desk Calendar           18.0
Desk Chair Mat          22.0
Desk Lamp               45.0
Desk Lamp with USB      68.0
Desk Organizer          65.0
Desk Pad                28.0
Document Scanner       140.0
File Cabinet           180.0
Headphones             150.0
Highlighters             3.5
Index Cards              0.8
Keyboard                80.0
Laptop                1242.0
Monitor                220.0
Monitor Stand           55.0
Mouse                   35.0
Notebook                 5.0
Office Chair           300.0
Office Plant            35.0
Paper Shredder          75.0
Pen                      1.5
Power Strip             18.0
Printer Paper            8.0
Standing Desk          450.0
Stapler                 12.0
Sticky Notes             4.0
Tablet Stand            28.0
USB Drive               25.0
USB Hub                 32.0
Webcam                  85.0
Whiteboard             120.0
Wireless Earbuds       125.0
Wireless Keyboard      110.0
Wireless Mouse          45.0
Name: Price, dtype: float64

In [103]:
df.sort_values('Product', ascending=False)

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,POLAND
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,SOUTH KOREA
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,SAUDI ARABIA
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,FRANCE
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,MOROCCO
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,SPAIN
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,SWEDEN
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,PAKISTAN
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,AUSTRALIA
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,EGYPT
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,SOUTH KOREA
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,ITALY
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,FRANCE
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,GERMANY
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,JAPAN
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,SOUTH KOREA
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,UNITED STATES
32,1033,Sofia Rodriguez,Laptop,Furniture,1,42.0,2024-07-04,No,COLOMBIA
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,MEXICO
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,UNITED STATES
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,CANADA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,CANADA
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,INDIA
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,GERMANY
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,UNITED STATES
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,SINGAPORE
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,ARGENTINA
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,ITALY
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,JAPAN
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,CHINA
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,BRAZIL
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,RUSSIA

In [105]:
df.sort_values('Price', ascending=True)

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,UNITED STATES
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,ITALY
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,RUSSIA
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,CANADA
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,PAKISTAN
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,EGYPT
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,AUSTRALIA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,JAPAN
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,ITALY
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,SOUTH KOREA
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,ARGENTINA
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,SPAIN
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,SWEDEN
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,MOROCCO
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,GERMANY
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,JAPAN
32,1033,Sofia Rodriguez,Laptop,Furniture,1,42.0,2024-07-04,No,COLOMBIA
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,SINGAPORE
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,POLAND
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,UNITED STATES
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,FRANCE
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,MEXICO
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,FRANCE
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,BRAZIL
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,SOUTH KOREA
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,SAUDI ARABIA
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
31,1032,Thomas Müller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,GERMANY
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,CANADA
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,INDIA
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,SOUTH KOREA
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,CHINA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,UNITED STATES

In [ ]:
df.to_csv('new_file.csv', index=True)
# To save new file