In [1]:
import pandas as pd
data = [1,2,3,4,'apple']

#convert the list into panda series
series = pd.Series(data, index=[101,102,103,104,105])
print(series)

101        1
102        2
103        3
104        4
105    apple
dtype: object

In [2]:

weeks={
    "Day1":"Monday",
    "Day2":"Tuesday",
    "Day3":"Wednesday",
    "Day4":"Thursday",
    "Day5":"Friday",
    "Day6":"Saturday",
    "Day7":"Sunday"
}

day_series = pd.Series(weeks)
print(day_series)
print("\n Series created from a dictionary")
print("\n First element using iloc:")
print(day_series.iloc[0])

Day1       Monday
Day2      Tuesday
Day3    Wednesday
Day4     Thursday
Day5       Friday
Day6     Saturday
Day7       Sunday
dtype: object

 Series created from a dictionary

 First element using iloc:
Monday

In [3]:
#dictionary containing data
dataset={
    'name':['Jhon','Rahul','Arun'],'age':[29,34,32]
}
df = pd.DataFrame(dataset)   #DataFrame is used to show data in excel format
print(df)
print(df.loc[1]) #access the element with index

    name  age
0   Jhon   29
1  Rahul   34
2   Arun   32
name    Rahul
age        34
Name: 1, dtype: object

In [4]:

data = [1,2,3,4,5]

#convert the list into panda series
series = pd.Series(data, index=[101,102,103,104,105])
print(series[series>3])

104    4
105    5
dtype: int64

In [5]:
##  Series from a list with filtering
# -----------------------------------------------------
# Task:
# - Create a Series from the list [10, 20, 30, 40, 50]
# - Use loc[] to access the element with index 3
# - Use iloc[] to access the second element
# - Filter and print elements greater than 25

l = [10,20,30,40,50]
a = pd.Series(l)
print(a.loc[3])
print(a.iloc[1]) 
print(a[a>25])

40
20
2    30
3    40
4    50
dtype: int64

In [6]:
#  Series from a dictionary
# -----------------------------------------------------
# Task:
# - Create a Series from the dictionary: {"A": 5, "B": 15, "C": 25, "D": 35}
# - Access the value of key "B" using loc[]
# - Access the first element using iloc[]
# - Filter and print values greater than 20

dic = {"A":5,"B":15,"C":25,"D":35}
b = pd.Series(dic)
print(b.loc["B"])
print(b.iloc[0])
print(b[b>20])

15
5
C    25
D    35
dtype: int64

In [7]:
# DataFrame from a dictionary
# -----------------------------------------------------
# Task:
# - Create a DataFrame with columns: "Name", "Age", "City"
#   Data: ["Alice", "Bob", "Charlie"], [25, 30, 35], ["Delhi", "Mumbai", "Chennai"]
# - Print the entire DataFrame
# - Print the row at index 1 using loc[]
# - Print the first row using iloc[]

t = { "Name":["Alice","Bob","Charlie"],"Age":[25,30,35],"City":["Delhi","Mumbai","Chennai"]}
c = pd.DataFrame(t)
print(c)
print(c.loc[1])
print(c.iloc[0])


#  Conditional filtering in DataFrame
# -----------------------------------------------------
# Task:
# - Using the above DataFrame, filter rows where Age > 28
# - Filter rows where City is "Delhi"
# - Print the filteredÂ DataFrames

print(c[c["Age"]>28])
print(c[c["City"]=="Delhi"])

      Name  Age     City
0    Alice   25    Delhi
1      Bob   30   Mumbai
2  Charlie   35  Chennai
Name       Bob
Age         30
City    Mumbai
Name: 1, dtype: object
Name    Alice
Age        25
City    Delhi
Name: 0, dtype: object
      Name  Age     City
1      Bob   30   Mumbai
2  Charlie   35  Chennai
    Name  Age   City
0  Alice   25  Delhi

In [8]:
order = pd.read_csv("orders.csv")
print(order.to_string())

    OrderID      CustomerName                Product     Category  Quantity   Price   OrderDate Shipped       Country
0      1001        John Smith                 Laptop  Electronics         1  1200.0  2024-06-01     Yes           USA
1      1002         Sarah Lee             Headphones  Electronics         2   150.0  2024-06-03      No        Canada
2      1003          Ali Khan           Office Chair    Furniture         1   300.0  2024-06-04     Yes           UAE
3      1004        Alice Wong              Desk Lamp    Furniture         3    45.0  2024-06-05     Yes     Singapore
4      1005     Carlos Mendez               Keyboard  Electronics         2    80.0  2024-06-06      No        Mexico
5      1006      Nora Ibrahim               Notebook   Stationery         5     5.0  2024-06-07     Yes           UAE
6      1007       Emily Davis          Standing Desk    Furniture         1   450.0  2024-06-08     Yes            UK
7      1008        James Park                Monitor  Electronics         2   220.0  2024-06-09      No   South Korea
8      1009       Maria Rossi                    Pen   Stationery        10     1.5  2024-06-10     Yes         Italy
9      1010  Takeshi Nakamura                  Mouse  Electronics         1    35.0  2024-06-11     Yes         Japan
10     1011     Sophie Martin                 Webcam  Electronics         1    85.0  2024-06-12     Yes        France
11     1012         Raj Patel           File Cabinet    Furniture         2   180.0  2024-06-13      No         India
12     1013       Emma Wilson                Stapler   Stationery         3    12.0  2024-06-14     Yes     Australia
13     1014   Diego Rodriguez              USB Drive  Electronics         5    25.0  2024-06-15     Yes         Spain
14     1015         Lisa Chen              Bookshelf    Furniture         1   280.0  2024-06-16      No         China
15     1016      Ahmed Hassan          Printer Paper   Stationery        20     8.0  2024-06-17     Yes         Egypt
16     1017     Anna Kowalski         Wireless Mouse  Electronics         2    45.0  2024-06-18     Yes        Poland
17     1018     Michael Brown         Desk Organizer    Furniture         1    65.0  2024-06-19      No           USA
18     1019       Yuki Tanaka             Calculator  Electronics         1    15.0  2024-06-20     Yes         Japan
19     1020   Fatima Al-Zahra             Whiteboard    Furniture         1   120.0  2024-06-21     Yes  Saudi Arabia
20     1021    David Thompson           Highlighters   Stationery         8     3.5  2024-06-22      No        Canada
21     1022    Isabella Silva      Bluetooth Speaker  Electronics         1    95.0  2024-06-23     Yes        Brazil
22     1023    Oliver Schmidt           Office Plant    Furniture         2    35.0  2024-06-24     Yes       Germany
23     1024        Zara Ahmed           Sticky Notes   Stationery        15     4.0  2024-06-25      No      Pakistan
24     1025    Lucas Anderson           Tablet Stand  Electronics         1    28.0  2024-06-26     Yes        Sweden
25     1026      Chloe Dubois         Paper Shredder  Electronics         1    75.0  2024-06-27     Yes        France
26     1027     Miguel Torres         Desk Chair Mat    Furniture         1    22.0  2024-06-28      No     Argentina
27     1028       Nina Petrov           Binder Clips   Stationery        12     2.5  2024-06-29     Yes        Russia
28     1029      Seo-yeon Kim      Wireless Keyboard  Electronics         1   110.0  2024-06-30     Yes   South Korea
29     1030   Giuseppe Romano          Desk Calendar    Furniture         1    18.0  2024-07-01      No         Italy
30     1031      Amira Hassan                USB Hub  Electronics         1    32.0  2024-07-02     Yes       Morocco
31     1032     Thomas MÃ¼ller       Document Scanner  Electronics         1   140.0  2024-07-03     Yes       Germany
32     1033   Sofia Rodriguez  Desk Drawer Organizer    Furniture         1    42.0  2024-07-04      No      Colombia
33     1034      Alex Johnson            Index Cards   Stationery       100     0.8  2024-07-05     Yes           USA
34     1035     Yuki Yamamoto          Monitor Stand  Electronics         1    55.0  2024-07-06     Yes         Japan
35     1036     Emma Thompson     Desk Lamp with USB    Furniture         1    68.0  2024-07-07      No            UK
36     1037     Carlos Santos       Wireless Earbuds  Electronics         1   125.0  2024-07-08     Yes      Portugal
37     1038    Leila Mansouri               Desk Pad    Furniture         1    28.0  2024-07-09     Yes          Iran
38     1039        Daniel Kim            Power Strip  Electronics         2    18.0  2024-07-10      No   South Korea
39     1040      Anna Ivanova             Desk Clock    Furniture         1    35.0  2024-07-11     Yes       Ukraine

In [9]:
order.head()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico

In [10]:
order[['Category','Country']] #specific columns

       Category       Country
0   Electronics           USA
1   Electronics        Canada
2     Furniture           UAE
3     Furniture     Singapore
4   Electronics        Mexico
5    Stationery           UAE
6     Furniture            UK
7   Electronics   South Korea
8    Stationery         Italy
9   Electronics         Japan
10  Electronics        France
11    Furniture         India
12   Stationery     Australia
13  Electronics         Spain
14    Furniture         China
15   Stationery         Egypt
16  Electronics        Poland
17    Furniture           USA
18  Electronics         Japan
19    Furniture  Saudi Arabia
20   Stationery        Canada
21  Electronics        Brazil
22    Furniture       Germany
23   Stationery      Pakistan
24  Electronics        Sweden
25  Electronics        France
26    Furniture     Argentina
27   Stationery        Russia
28  Electronics   South Korea
29    Furniture         Italy
30  Electronics       Morocco
31  Electronics       Germany
32    Furniture      Colombia
33   Stationery           USA
34  Electronics         Japan
35    Furniture            UK
36  Electronics      Portugal
37    Furniture          Iran
38  Electronics   South Korea
39    Furniture       Ukraine

In [11]:
order.tail()  #last rows

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [12]:
order.info()  #information about order

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       40 non-null     int64
 1   CustomerName  40 non-null     object
 2   Product       40 non-null     object
 3   Category      40 non-null     object
 4   Quantity      40 non-null     int64
 5   Price         40 non-null     float64
 6   OrderDate     40 non-null     object
 7   Shipped       40 non-null     object
 8   Country       40 non-null     object
dtypes: float64(1), int64(2), object(6)
memory usage: 2.9+ KB

In [13]:
order.iloc[0]

OrderID                1001
CustomerName     John Smith
Product              Laptop
Category        Electronics
Quantity                  1
Price                1200.0
OrderDate        2024-06-01
Shipped                 Yes
Country                 USA
Name: 0, dtype: object

In [14]:
order[(order['Category'] == 'Electronics') & (order['Country'] == 'Japan')]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan

In [15]:
order[(order['Category'] == 'Electronics') | (order['Country'] == 'Japan')]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas MÃ¼ller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea

In [16]:
order[(order['Price'] > 1000) & (order['Country'] == 'USA')]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA

In [ ]:
order[~(order['Price'] > 10) ]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [18]:
order[order['CustomerName'].str.startswith('A')]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [19]:
order[order['CustomerName'].str.endswith('a')]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [20]:
order[order['Country'].isin(['Japan','USA','UAE'])]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,USA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,Japan
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,Japan
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,Japan

In [21]:
order[~order['Country'].isin(['Japan','USA','UAE'])]

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,Canada
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,Singapore
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,Mexico
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,South Korea
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,Italy
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,France
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,India
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,Australia
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,Spain
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,China
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,Egypt
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,Saudi Arabia
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,Canada
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,Brazil
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,Germany
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,Pakistan
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,Sweden
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,France
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,Argentina
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,Russia
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,Italy
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,Morocco
31,1032,Thomas MÃ¼ller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,Germany
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,Colombia
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,Portugal
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,Iran
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,South Korea
39,1040,Anna Ivanova,Desk Clock,Furniture,1,35.0,2024-07-11,Yes,Ukraine

In [27]:
order["Price"].unique()

array([1.20e+03, 1.50e+02, 3.00e+02, 4.50e+01, 8.00e+01, 5.00e+00,
       4.50e+02, 2.20e+02, 1.50e+00, 3.50e+01, 8.50e+01, 1.80e+02,
       1.20e+01, 2.50e+01, 2.80e+02, 8.00e+00, 6.50e+01, 1.50e+01,
       1.20e+02, 3.50e+00, 9.50e+01, 4.00e+00, 2.80e+01, 7.50e+01,
       2.20e+01, 2.50e+00, 1.10e+02, 1.80e+01, 3.20e+01, 1.40e+02,
       4.20e+01, 8.00e-01, 5.50e+01, 6.80e+01, 1.25e+02])

In [28]:
order.loc[order['CustomerName'] == 'Seo-yeon Kim']

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
28,1029,Seo-yeon Kim,Wireless Keyboard,Electronics,1,110.0,2024-06-30,Yes,South Korea

In [30]:
order.loc[order['CustomerName'] == 'Seo-yeon Kim' , 'Product'] = 'Mouse'

In [31]:
order.loc[order['CustomerName'] == 'Seo-yeon Kim']

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
28,1029,Seo-yeon Kim,Mouse,Electronics,1,110.0,2024-06-30,Yes,South Korea

In [37]:
order['Product'].max()

'Wireless Mouse'

In [38]:
order.loc[order['Product'] == 'Wireless Mouse']

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,Poland

In [39]:
order.loc[order['Product'] == 'Wireless Mouse' , 'Country'] = 'India'

In [41]:
order.loc[order['Product'] == 'Wireless Mouse']

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,India

In [42]:
order['Country'] = order['Country'].str.upper()

In [43]:
order['Country']

0            INDIA
1           CANADA
2              UAE
3        SINGAPORE
4           MEXICO
5              UAE
6               UK
7      SOUTH KOREA
8            ITALY
9            JAPAN
10          FRANCE
11           INDIA
12       AUSTRALIA
13           SPAIN
14           CHINA
15           EGYPT
16           INDIA
17             USA
18           JAPAN
19    SAUDI ARABIA
20          CANADA
21          BRAZIL
22         GERMANY
23        PAKISTAN
24          SWEDEN
25          FRANCE
26       ARGENTINA
27          RUSSIA
28     SOUTH KOREA
29           ITALY
30         MOROCCO
31         GERMANY
32        COLOMBIA
33             USA
34           JAPAN
35              UK
36        PORTUGAL
37            IRAN
38     SOUTH KOREA
39         UKRAINE
Name: Country, dtype: object

In [45]:
order = order.drop(39)

In [46]:
order.tail()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,SOUTH KOREA

In [47]:
order.dropna()

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,INDIA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,CANADA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,SINGAPORE
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,MEXICO
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,SOUTH KOREA
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,ITALY
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,JAPAN
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,FRANCE
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,INDIA
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,AUSTRALIA
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,SPAIN
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,CHINA
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,EGYPT
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,INDIA
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,JAPAN
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,SAUDI ARABIA
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,CANADA
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,BRAZIL
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,GERMANY
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,PAKISTAN
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,SWEDEN
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,FRANCE
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,ARGENTINA
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,RUSSIA
28,1029,Seo-yeon Kim,Mouse,Electronics,1,110.0,2024-06-30,Yes,SOUTH KOREA
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,ITALY
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,MOROCCO
31,1032,Thomas MÃ¼ller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,GERMANY
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,COLOMBIA
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,SOUTH KOREA

In [62]:
order.fillna({"OrderID":0}, inplace=False)

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,INDIA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,CANADA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,SINGAPORE
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,MEXICO
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,SOUTH KOREA
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,ITALY
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,JAPAN
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,FRANCE
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,INDIA
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,AUSTRALIA
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,SPAIN
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,CHINA
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,EGYPT
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,INDIA
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,JAPAN
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,SAUDI ARABIA
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,CANADA
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,BRAZIL
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,GERMANY
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,PAKISTAN
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,SWEDEN
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,FRANCE
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,ARGENTINA
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,RUSSIA
28,1029,Seo-yeon Kim,Mouse,Electronics,1,110.0,2024-06-30,Yes,SOUTH KOREA
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,ITALY
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,MOROCCO
31,1032,Thomas MÃ¼ller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,GERMANY
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,COLOMBIA
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,SOUTH KOREA

In [61]:
order.rename(columns={'OrderID': 'Order ID'},inplace=0)

,Order ID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,INDIA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,CANADA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,SINGAPORE
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,MEXICO
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,SOUTH KOREA
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,ITALY
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,JAPAN
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,FRANCE
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,INDIA
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,AUSTRALIA
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,SPAIN
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,CHINA
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,EGYPT
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,INDIA
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,JAPAN
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,SAUDI ARABIA
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,CANADA
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,BRAZIL
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,GERMANY
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,PAKISTAN
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,SWEDEN
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,FRANCE
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,ARGENTINA
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,RUSSIA
28,1029,Seo-yeon Kim,Mouse,Electronics,1,110.0,2024-06-30,Yes,SOUTH KOREA
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,ITALY
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,MOROCCO
31,1032,Thomas MÃ¼ller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,GERMANY
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,COLOMBIA
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,SOUTH KOREA

In [63]:
order['Country'].value_counts()

Country
INDIA           3
JAPAN           3
SOUTH KOREA     3
CANADA          2
UAE             2
UK              2
ITALY           2
FRANCE          2
USA             2
GERMANY         2
SINGAPORE       1
MEXICO          1
AUSTRALIA       1
SPAIN           1
EGYPT           1
CHINA           1
SAUDI ARABIA    1
BRAZIL          1
PAKISTAN        1
SWEDEN          1
ARGENTINA       1
RUSSIA          1
MOROCCO         1
COLOMBIA        1
PORTUGAL        1
IRAN            1
Name: count, dtype: int64

In [ ]:
order.groupby("Country").Quantity.sum() #summarize data based on categories

Country
ARGENTINA         1
AUSTRALIA         3
BRAZIL            1
CANADA           10
CHINA             1
COLOMBIA          1
EGYPT            20
FRANCE            2
GERMANY           3
INDIA             5
IRAN              1
ITALY            11
JAPAN             3
MEXICO            2
MOROCCO           1
PAKISTAN         15
PORTUGAL          1
RUSSIA           12
SAUDI ARABIA      1
SINGAPORE         3
SOUTH KOREA       5
SPAIN             5
SWEDEN            1
UAE               6
UK                2
USA             101
Name: Quantity, dtype: int64

In [66]:
order.groupby('Product').Quantity.sum()

Product
Binder Clips              12
Bluetooth Speaker          1
Bookshelf                  1
Calculator                 1
Desk Calendar              1
Desk Chair Mat             1
Desk Drawer Organizer      1
Desk Lamp                  3
Desk Lamp with USB         1
Desk Organizer             1
Desk Pad                   1
Document Scanner           1
File Cabinet               2
Headphones                 2
Highlighters               8
Index Cards              100
Keyboard                   2
Laptop                     1
Monitor                    2
Monitor Stand              1
Mouse                      2
Notebook                   5
Office Chair               1
Office Plant               2
Paper Shredder             1
Pen                       10
Power Strip                2
Printer Paper             20
Standing Desk              1
Stapler                    3
Sticky Notes              15
Tablet Stand               1
USB Drive                  5
USB Hub                    1
Webcam                     1
Whiteboard                 1
Wireless Earbuds           1
Wireless Mouse             2
Name: Quantity, dtype: int64

In [67]:
order

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,INDIA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,CANADA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,SINGAPORE
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,MEXICO
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,SOUTH KOREA
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,ITALY
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,JAPAN
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,FRANCE
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,INDIA
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,AUSTRALIA
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,SPAIN
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,CHINA
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,EGYPT
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,INDIA
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,JAPAN
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,SAUDI ARABIA
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,CANADA
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,BRAZIL
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,GERMANY
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,PAKISTAN
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,SWEDEN
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,FRANCE
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,ARGENTINA
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,RUSSIA
28,1029,Seo-yeon Kim,Mouse,Electronics,1,110.0,2024-06-30,Yes,SOUTH KOREA
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,ITALY
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,MOROCCO
31,1032,Thomas MÃ¼ller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,GERMANY
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,COLOMBIA
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,SOUTH KOREA

In [68]:
order.sort_values('Price',ascending=True)

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,ITALY
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,RUSSIA
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,CANADA
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,PAKISTAN
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,EGYPT
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,AUSTRALIA
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,JAPAN
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,ITALY
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,SOUTH KOREA
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,ARGENTINA
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,SPAIN
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,SWEDEN
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,MOROCCO
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,GERMANY
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,JAPAN
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,COLOMBIA
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,SINGAPORE
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,INDIA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,FRANCE
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,MEXICO
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,FRANCE
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,BRAZIL
28,1029,Seo-yeon Kim,Mouse,Electronics,1,110.0,2024-06-30,Yes,SOUTH KOREA
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,SAUDI ARABIA
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
31,1032,Thomas MÃ¼ller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,GERMANY
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,CANADA
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,INDIA
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,SOUTH KOREA
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,CHINA
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,INDIA

In [70]:
order.sort_values('Price',ascending=False)

,OrderID,CustomerName,Product,Category,Quantity,Price,OrderDate,Shipped,Country
0,1001,John Smith,Laptop,Electronics,1,1200.0,2024-06-01,Yes,INDIA
6,1007,Emily Davis,Standing Desk,Furniture,1,450.0,2024-06-08,Yes,UK
2,1003,Ali Khan,Office Chair,Furniture,1,300.0,2024-06-04,Yes,UAE
14,1015,Lisa Chen,Bookshelf,Furniture,1,280.0,2024-06-16,No,CHINA
7,1008,James Park,Monitor,Electronics,2,220.0,2024-06-09,No,SOUTH KOREA
11,1012,Raj Patel,File Cabinet,Furniture,2,180.0,2024-06-13,No,INDIA
1,1002,Sarah Lee,Headphones,Electronics,2,150.0,2024-06-03,No,CANADA
31,1032,Thomas MÃ¼ller,Document Scanner,Electronics,1,140.0,2024-07-03,Yes,GERMANY
36,1037,Carlos Santos,Wireless Earbuds,Electronics,1,125.0,2024-07-08,Yes,PORTUGAL
19,1020,Fatima Al-Zahra,Whiteboard,Furniture,1,120.0,2024-06-21,Yes,SAUDI ARABIA
28,1029,Seo-yeon Kim,Mouse,Electronics,1,110.0,2024-06-30,Yes,SOUTH KOREA
21,1022,Isabella Silva,Bluetooth Speaker,Electronics,1,95.0,2024-06-23,Yes,BRAZIL
10,1011,Sophie Martin,Webcam,Electronics,1,85.0,2024-06-12,Yes,FRANCE
4,1005,Carlos Mendez,Keyboard,Electronics,2,80.0,2024-06-06,No,MEXICO
25,1026,Chloe Dubois,Paper Shredder,Electronics,1,75.0,2024-06-27,Yes,FRANCE
35,1036,Emma Thompson,Desk Lamp with USB,Furniture,1,68.0,2024-07-07,No,UK
17,1018,Michael Brown,Desk Organizer,Furniture,1,65.0,2024-06-19,No,USA
34,1035,Yuki Yamamoto,Monitor Stand,Electronics,1,55.0,2024-07-06,Yes,JAPAN
3,1004,Alice Wong,Desk Lamp,Furniture,3,45.0,2024-06-05,Yes,SINGAPORE
16,1017,Anna Kowalski,Wireless Mouse,Electronics,2,45.0,2024-06-18,Yes,INDIA
32,1033,Sofia Rodriguez,Desk Drawer Organizer,Furniture,1,42.0,2024-07-04,No,COLOMBIA
9,1010,Takeshi Nakamura,Mouse,Electronics,1,35.0,2024-06-11,Yes,JAPAN
22,1023,Oliver Schmidt,Office Plant,Furniture,2,35.0,2024-06-24,Yes,GERMANY
30,1031,Amira Hassan,USB Hub,Electronics,1,32.0,2024-07-02,Yes,MOROCCO
24,1025,Lucas Anderson,Tablet Stand,Electronics,1,28.0,2024-06-26,Yes,SWEDEN
37,1038,Leila Mansouri,Desk Pad,Furniture,1,28.0,2024-07-09,Yes,IRAN
13,1014,Diego Rodriguez,USB Drive,Electronics,5,25.0,2024-06-15,Yes,SPAIN
26,1027,Miguel Torres,Desk Chair Mat,Furniture,1,22.0,2024-06-28,No,ARGENTINA
38,1039,Daniel Kim,Power Strip,Electronics,2,18.0,2024-07-10,No,SOUTH KOREA
29,1030,Giuseppe Romano,Desk Calendar,Furniture,1,18.0,2024-07-01,No,ITALY
18,1019,Yuki Tanaka,Calculator,Electronics,1,15.0,2024-06-20,Yes,JAPAN
12,1013,Emma Wilson,Stapler,Stationery,3,12.0,2024-06-14,Yes,AUSTRALIA
15,1016,Ahmed Hassan,Printer Paper,Stationery,20,8.0,2024-06-17,Yes,EGYPT
5,1006,Nora Ibrahim,Notebook,Stationery,5,5.0,2024-06-07,Yes,UAE
23,1024,Zara Ahmed,Sticky Notes,Stationery,15,4.0,2024-06-25,No,PAKISTAN
20,1021,David Thompson,Highlighters,Stationery,8,3.5,2024-06-22,No,CANADA
27,1028,Nina Petrov,Binder Clips,Stationery,12,2.5,2024-06-29,Yes,RUSSIA
8,1009,Maria Rossi,Pen,Stationery,10,1.5,2024-06-10,Yes,ITALY
33,1034,Alex Johnson,Index Cards,Stationery,100,0.8,2024-07-05,Yes,USA

In [71]:
order.to_csv('new_file.csv',index=True)